{{- if not .Values.policy.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tg.policyConfigMap" . }}
  labels: {{- include "tg.labels" . | nindent 4 }}
data:
  policy.yaml: |
{{- if .Values.policy.content }}
{{ .Values.policy.content | indent 4 }}
{{- else }}
{{ .Files.Get "files/policy.yaml" | indent 4 }}
{{- end }}
  inventory.yaml: |
{{- if .Values.policy.inventoryContent }}
{{ .Values.policy.inventoryContent | indent 4 }}
{{- else }}
{{ .Files.Get "files/inventory.yaml" | indent 4 }}
{{- end }}
{{- end }}
