{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tg.secretName" . }}
  labels: {{- include "tg.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets }}
  {{- if .adminToken }}
  admin-token: {{ .adminToken | quote }}
  {{- end }}
  {{- if .upstreamExternalKey }}
  upstream-external-key: {{ .upstreamExternalKey | quote }}
  {{- end }}
  {{- if .upstreamInternalKey }}
  upstream-internal-key: {{ .upstreamInternalKey | quote }}
  {{- end }}
  {{- if .upstreamAnthropicKey }}
  upstream-anthropic-key: {{ .upstreamAnthropicKey | quote }}
  {{- end }}
  {{- if .clickhousePassword }}
  clickhouse-password: {{ .clickhousePassword | quote }}
  {{- end }}
  {{- end }}
{{- end }}
