{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tg.serviceAccountName" . }}
  labels: {{- include "tg.labels" . | nindent 4 }}
# Gateway Kubernetes API'sine erişmez
automountServiceAccountToken: false
{{- end }}
